#
# Copyright (c) 2025-2026 Ola Lundqvist <ola@inguza.com>
#
# Licensed under the GNU General Public License v3.0.
# See LICENSE-GPLv3.txt for the full license text.
# Commercial licensing is available separately.
#

###################################################################################
# Load the general bashrc
###################################################################################
if [[ -e "$HOME/.bashrc" ]] ; then
   . "$HOME/.bashrc"
fi

###################################################################################
# specific maia functionality
###################################################################################
# Alias to set the session in a way that save keystrokes
maias() {
    export MAIA_SESSION="$1"
}
# Prompt visibility
if [[ -n "$MAIA_PS1" ]] ; then
    PS1="$MAIA_PS1"
fi
maia_prompt_helper() {
    MAIA_PROMPT_SESSION=$(maia --query session)
    MAIA_PROMPT_WORKSPACE=$(maia --query workspace)
}
if [[ "$PROMPT_COMMAND" != *maia_prompt_helper* ]]; then
    if [[ -z "$PROMPT_COMMAND" ]] ; then
	PROMPT_COMMAND="maia_prompt_helper > /dev/null 2>&1 || true"
    else
	PROMPT_COMMAND+=$'\n'"maia_prompt_helper > /dev/null 2>&1 || true"
    fi
fi
# Bash completions
. "${MAIA_ROOT}/etc/bash.completions"
