# The Alias for the command. You need to change the path to the maia executable
if [[ -e "$HOME/.bashrc" ]] ; then
   . "$HOME/.bashrc"
fi
maias() {
    export MAIA_SESSION="$1"
}
if [[ -n "$MAIA_PS1" ]] ; then
    export PS1="$MAIA_PS1"
fi
maia_prompt_helper() {
    export MAIA_PROMPT_SESSION=$(maia --query session)
    export MAIA_PROMPT_WORKSPACE=$(maia --query workspace)
}
export PROMPT_COMMAND="maia_prompt_helper"
